version: "3.8"

services:

  proxy:
    image: ${SERVICE_NAME}
    build:
      context: .
    volumes:
      - ${DOCKER_WORKDIR}:/app
    environment:
      REDIS_URLS: "redis:10001,redis:10002,redis:10003"
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
    networks:
      stateful_proxy_network:
        ipv4_address: 172.20.0.3
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis-cluster
    build:
      context: redis
    ports:
      - 10001:10001
      - 10002:10002
      - 10003:10003
    healthcheck:
       test: ["CMD", "redis-cli", "-c", "-p", "10001", "ping"]
    sysctls:
        - net.core.somaxconn=4096
    networks:
      stateful_proxy_network:
        ipv4_address: 172.20.0.2

  redis-cli:
    image: redis:alpine
    networks:
      stateful_proxy_network:
        ipv4_address: 172.20.0.4

networks:
  stateful_proxy_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
