version: "3.8"

services:

  proxy:
    image: ${SERVICE_NAME}
    build:
      context: .
    volumes:
      - ${DOCKER_WORKDIR}:/app
    environment:
      REDIS_URL: "redis://user:pass@redis:6379"
    depends_on:
      - redis

  redis:
    image: redis-cluster
    build:
      context: redis
